### ISSUE TITLE
imageUrl can't use image from local

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-fresco#18]
I am using v1.0.7 (not 1.0.8 as 1.0.8 required addition angular module which I am not using angular, Can you make angular as optional or separate version). 

The local image works on ie placeholderImageUrl but NOT imageUrl.

WORK:

```
    <fresco:FrescoDrawee width="250" height="250"
          placeholderImageUri="~/images/noone.jpg"/>
```

NOT WORK

```
    <fresco:FrescoDrawee width="250" height="250"
         imageUri="~/images/noone.jpg"/>
```

**Comment by VladimirAmiorkov** [comment]
Hi @ryc16 ,

Currently the `imageUri` as stated by its [description](https://github.com/NativeScript/nativescript-fresco#basic-attributes) in the readme only supports remote (http, https) and from the resources files of your {N} application URIs (res://yourImageNameWithOutExtension). For more details about all of the features of the plugin please refer the [Features](https://github.com/NativeScript/nativescript-fresco#features) section from the readme.

If you would like I can tag this thread as a "feature" but first could you share with me the scenarios where using local files instead of local resources is preferable. This will help with evaluating the priority of such feature.

On a side note I have reverted the "angular compatibility feature" for now so feel free to again use the latest ^1.0.10 version of the plugin.

**Comment by ryc16** [comment]
@VladimirAmiorkov, thanks for your answer, yes, please thread this as feature. I wish it supports local file since other properties support local file already. Here is my example, if I want to build an app to show picture from mobile picture folder in addition from remote, we could still use fresco to have same UX experience. 

By the way, is there a plan to have it on IOS so that we could have same UX and keep one implementation or declaration.

Also, does placeholderImageUri image would keep the same size specified in property in width and height if my placeholderImageUrl image different size. Currently, it is not. my placeholderImageUrl is small than width 250, height 250, but I want to stretch to 250. Can't find any property to specify this.

```
    <fresco:FrescoDrawee width="250" height="250"
          placeholderImageUri="~/images/noone.jpg"/>
```

Thanks for reverted the angular feature.

**Comment by VladimirAmiorkov** [comment]
@ryc16 

I will give it a try, initially before 1.0.0 I was working on this and was close to solving it but got pushed back by Android Java specific limitations of the Fresco library. Keep track of this thread for future updates. 

Regarding expanding this plugin to iOS, we have thought about this and we do want to make this happen. Its a bit tricky as currently there is no iOS native library that is utilized the same way as the Android Fresco library. Currently we have brainstormed two options, implement an iOS extension inside this plugin and in the perfect scenario cover most of the Fresco features with iOS counterparts or create a separate iOS plugin and implement its API as close as possible to the nativescript-fresco plugin. If you could open a separate issue regarding expanding the plugin to iOS it would be great so that we can move the discussion there.

**Comment by Daxito** [comment]
+1

**Comment by andreasotto** [comment]
+1

**Comment by Daxito** [comment]
Just waiting for the PR to be approved and available from npm! Thanks @triniwiz !

**Comment by VladimirAmiorkov** [comment]
Resolved with https://github.com/NativeScript/nativescript-fresco/pull/22

**Comment by VladimirAmiorkov** [comment]
Cheers @triniwiz , PR is merged and I have updated the npm package with 1.0.12 version.

CC @Daxito
