### ISSUE TITLE
Rounded corner radius doesn't work on Angular project

### ISSUE THREAD

**Issue by ghost** [NativeScript/nativescript-fresco#55]
Round as circle work like a charm, but when I try to set the rounded corner radius, nothing happens. I've tryed to put the rounded style on css, but doesn't work too if I'm using the Fresco Drawee (works with Image).

**Comment by DimitarTodorov** [comment]
Hi @hypertenso, 

In order to see the behavior of the 'roundedCornerRadius' property you should set to true at least one of the four additional boolean properties - roundBottomRight, roundBottomLeft, roundTopRight, roundTopLeft - which are used to point where exactly the rounded corner radius value will be applied.

Here is an example:

    <FrescoDrawee #drawee verticalAlignment="center" placeholderImageUri="res://ns_logo" 
        aspectRatio="2" 
        roundedCornerRadius="50"
        roundBottomRight="true" 
        roundBottomLeft="true" 
        roundTopLeft="true" 
        roundTopRight="true" 
        imageUri="http://lorempixel.com/400/200/">
    </FrescoDrawee> 

Regards,
Dimitar

**Comment by ghost** [comment]
Oh man, you are the guy! Thank you!
