### ISSUE TITLE
Question: Can the plugin support ImageSource from nativescript?

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-fresco#9]
Will fresco cache the same image and only load once? For example, if I have listivew that has repeater fresco image with same link or resource image, will fresco load only once? One good example is the placeholderImageUri or failureImageUri. 

If fresco not cache same image url, might be it makes sense to have the plugin to support ImageSource.
Is it possible for the plugin supporting ImageSource currently?

**Comment by VladimirAmiorkov** [comment]
Hi @ryc16 ,

I am not sure I understand your question completely. By design the Facebook's Android Fresco library has multiple layers of cache mechanisms which work out of the box without additional implementations. Those cache mechanisms are of course available in the nativescript-fresco plugin. The nativescript ImageSource is utilized in [some parts](https://github.com/NativeScript/nativescript-fresco/blob/master/nativescript-fresco.android.ts#L413-L430) of the plugin already and I am not sure where it would be beneficial to be used again, could you elaborated on this a bit more. After looking at the Fresco documentations I noticed that there are some events that are currently not available in the nativescript-fresco plugin in like the `onNewResultImpl`. 

Do you feel like having such events like the once documented in [this article](http://frescolib.org/docs/caching.html) would be beneficial to the plugin?

**Comment by ryc16** [comment]
Hi @VladimirAmiorkov,

I think 
Haven't come to the conclusion what the problem I am facing. Let me tell you what I am facing. I was able to use image-cache currently and able to loading ~1000 records all at once. These ~1000 records have about half different images and half are same image. Since half image is the same, I create a imageSource in advance for the same image just put to Image src="image_source" to avoid reload the same image to avoid increase memory footprint. 

However, I couldn't use imageSource on imageUrl on the plugin because my understand is your plugin only support url. So after I replace Image with fresco and given the url string for ImageUrl. my app crash at the end. (still don't know why at this point).

By looked at your section you highlighted.

```
private getDrawableFromLocalFile(localFilePath: string) {
        var img = imageSource.fromFile(localFilePath);
        if (img) {
            var drawable = new android.graphics.drawable.BitmapDrawable(utils.ad.getApplicationContext().getResources(), img.android);
        }

        return drawable;
    }

    private getDrawableFromResource(resourceName: string) {
        var img = imageSource.fromResource(resourceName.substr(utils.RESOURCE_PREFIX.length));
        if (img) {
            var drawable = new android.graphics.drawable.BitmapDrawable(utils.ad.getApplicationContext().getResources(), img.android);
        }

        return drawable;
    }
}

```

It looks to me you are recreating imageSource with given url regardless even it is same url. I am not sure if it is new create of bitmap and how fresco could help. 

So i am thinking if your plugin can allow us to pass ImageSource to imageUrl, so at least I could pass the same imageSource and avoid to recreate imageSource from your code.

Please advice.

**Comment by VladimirAmiorkov** [comment]
@ryc16 

Thank you for sharing your scenario. I will think about it and give it a shot.

By design the Facebook's Fresco android library is designed to improve the memory management of showing local and remote images in an android application. Having preloaded an ~1000 images into an `ImageSource` might be an overkill in an mobile application as it might unnecessary worsen the performance of the app as those 1000 of images will probably not be viewed at once. Have you considered an "load on demand" solution for this feature of your application. For example our RadListView has such feature built-in into the component, more information can be found [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/load-on-demand).

**Comment by ryc16** [comment]
@VladimirAmiorkov,

I agree that preloading an ~1000 images is overkill but I am not sure if there is a better solution to balance the performance (fast scrolling) and memory usage. I was expecting and hoping fresco could do the work out of box. I did think of "load on demand" but I am not sure how it manage the memory. For example, if it is necessary to go to the last item (the 1000th) of list, first of all, I need to scroll many times, secondly, if RadListView just keep loading image without disposing early image, then memory will be still used up at the end.  Does nativesscript manage the memory by loading image only on visible element and free up if it is become invisible?

One good example for fast scrolling is your phone contact. Let say if you have 1000 friends with contact on your phone, and have avatar of many (ie half) of your friends. You might not want to use "load on demand" as it is too slow.

Please advice if there is solution to have a fast scrolling and keep the memory usage reasonable.

**Comment by VladimirAmiorkov** [comment]
Hi @ryc16 ,

The [RadListView](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview) component by default has virtualization built-in. This means that only the visible items (~3-7) are visualized  in the UI, all of the other items are stored as data item object. This means no matter how big the collection bound to the `items` property is unless the data object themselves (which are stored in the memory) are too big for example by storing an ImageSource for each item, there shouldn't be any performance issues.

There are many way that the above mentioned scenario could be implemented one is with the use of `loadOnDemandMode` set to `auto` or without an load on demand implementation with the nativescript-fresco plugin. By design the nativescript-fresco provided a way to asynchronously load an image from the web or local storage, show it in the view and mange it internally in the memory. What the android Fresco library is famous with is exactly this, it will cache the image in the memory and dispose of it automatically when it "decides" meaning that all of the downloaded images via the `imageUri` of the FrescoDrawee will be stored locally and after the app is reopened if one of those imageUri that has already been downloaded is in the memory it will not be downloaded again. With all that said in your scenario with the contact list example you could do the following:
- Set the `itemTemplate` of the RadListView to a template that contains the `FrescoDrawee`
- In the dataContext of the Page create a collection of objects that holds the 1000 records . Each object should have the "contactPictureUri" property that holds either the web or local uri location.

The final result would be that when the RadListView is scrolled really fast the "contact pictures" are not shown immediately as they are asynchronously being downloaded but when those "resources" have been dowloaded they will appear via the FrescoDrawee. This is just one way that this scenario could be approached, of course they are countless approaches and all could be considered "good" or "bad" for specific requirements. Hope this makes sense and is helpful.
